### ISSUE TITLE
Ctrl-b and Ctrl-/ not working like they do in Emacs

### ISSUE THREAD

**Issue by ghostandthemachine** [kpe/jupyterlab-emacskeys#1]
Thanks for sharing this, it has made my Jupyter life 1000% better. I am seeing issues with both Ctrl-b (emacs back char command) as well as Ctrl-/ (emacs undo command). The native JLab comment command is still overriding the emacs undo and the show sidebar is overriding back char. Is this something that could be dealt with from within this plugin? I can't seem to find a way to manually reset the show sidebar command.

Happy to move this to Stackoverflow if that's more appropriate but these issues seemed like :bug: s as they were not the expected behavior.

**Comment by kpe** [comment]
I'm also struggling with some of the default non-emacs bindings in JLab. My current 'solution' for `Ctrl-b` is to map the `toggle-left-area` to a different shortcut (`Ctl-'`) in the user overrides like this:
```
{
    // Keyboard Shortcuts
    // @jupyterlab/shortcuts-extension:plugin
    // Keyboard shortcut settings for JupyterLab.
    // ******************************************

    // [missing schema title]
    // [missing schema description]
    "application:toggle-left-area": {
      "command": "application:toggle-left-area",
      "keys": [
        "Ctrl '"
      ],
      "selector": "body",
      "title": "Toggle Left Area",
      "category": "Main Area"
    }
}
```

I hope one could also remap `Ctrl-/` or `Ctrl-Shift--` (the one I'm normally using) to something different, so the default CodeMirror bindings which would result in an undo as expected could be used. Until now however I was not able to found the corresponding `command`. (but let me look again)

**Comment by kpe** [comment]
I guess, I was able to kind of solve it, i.e. by setting `Ctrl-/` explicitly to `undo` in codemirror. I do the same for `Ctrl-Shift--` but to take effect you should also remap any existing shortcuts for it like this:
```
    // [missing schema title]
    // [missing schema description]
    "notebook:split-cell-at-cursor": {
      "command": "notebook:split-cell-at-cursor",
      "keys": [
        "Ctrl Alt Shift -"
      ],
      "selector": ".jp-Notebook.jp-mod-editMode",
      "title": "Split Cell at Cursor",
      "category": "Notebook Operations"
    }
```

**Comment by ghostandthemachine** [comment]
Awesome, thanks. This get's me close. I can't find an example of setting `Ctrl-/` in code mirror. Any chance you can share a snippet of that?

Much appreciated!

**Comment by kpe** [comment]
@ghostandthemachine - try reinstalling the extension - uninstall, then install from the extension manager (and then rebuild and reload when requested). The new version 0.4.1 contains the changes from the last commit 9faa02a, and should map/hardcode `Ctrl-/` to `undo` (so no additional configuration should be needed).

**Comment by ghostandthemachine** [comment]
Amazing! This made me go from hating the lab to loving it. Very much appreciated.

**Comment by rebcabin** [comment]
Into what file should one put these settings? This is just some json, but I have to put it somewhere. Where?

There are at least 3 possible locations, none of them look right (because they have "test" in their names):

find / -type f -print0 | xargs -0 -P 0 grep -n "Keyboard shortcut settings for JupyterLab" 2> /dev/null

~/anaconda3/envs/jup/lib/python3.10/site-packages/jupyterlab_server/test_data/schemas/@jupyterlab/shortcuts-extension/plugin.json:5:  "description": "Keyboard shortcut settings for JupyterLab.",

~/anaconda3/lib/python3.9/site-packages/jupyterlab_server/tests/schemas/@jupyterlab/shortcuts-extension/plugin.json:5:  "description": "Keyboard shortcut settings for JupyterLab.",

~/anaconda3/pkgs/jupyterlab_server-2.10.3-pyhd3eb1b0_1/site-packages/jupyterlab_server/tests/schemas/@jupyterlab/shortcuts-extension/plugin.json:5:  "description": "Keyboard shortcut settings for JupyterLab.",
